repos:
  - repo: https://git.iamthefij.com/iamthefij/ansible-pre-commit
    rev: 432d5e1242767157c3df5089bbeffd8055198be4 
    hooks:
      - id: encryption-check
        name: Ansible Vault Encryption Check
        description: Checks that vault files are encrypted
        entry: encryption-check.sh
        files: (ssh/.ssh/is_rsa)
        language: script
