#!/usr/bin/env bash
#
if [ $USER="paynen3" ]; then
    stow -D work
    stow work
else
    stow -D personal
    stow personal
fi

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    stow -D $folder
    stow $folder
done
eval ./shortcuts/.local/bin/multimonitor
eval ./shortcuts/.local/bin/launch_polybar 

popd
