#!/usr/bin/env zsh
STOW_FOLDERS="nvim,tmux,starship,zsh,ipython,i3,polybar,shortcuts,picom,ta,direnv"

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/dotfiles
fi
# for brew
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
export STOW_FOLDERS=$STOW_FOLDERS
export DOTFILES=$DOTFILES
export POLYBAR_BAR=home
eval $DOTFILES/install
