#!/usr/bin/env zsh
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="nvim,tmux,starship,zsh,ipython,vpn,proxy,i3,shortcuts"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/dotfiles
fi
# for brew
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
export STOW_FOLDERS=$STOW_FOLDERS
export DOTFILES=$DOTFILES
export HOME="/home/paynen3"
eval $DOTFILES/install
